### ISSUE TITLE
Remove 'defaults' conda channel.

### ISSUE THREAD

**Issue by james-vincent** [jianlin-cheng/CryoSegNet#8]
The Anaconda 'default's channel now requires a paid license for many institutions. Could you please rework the environment to use only conda-forge and not defaults?

**Comment by rajangyawali** [comment]
Thank you for raising this issue

**Comment by jjv5** [comment]
We very much prefer using pixi lately, instead of conda/mamba/miniconda etc. If it helps, here is the pixi.toml file that worked for us to install cryosegnet. It does not use the conda 'defaults' channel. This was installed on an Alma8 machine. 


```
[project]
name = "cryosegnet"
version = "1.0.0"
description = "cryo-EM protein particle picking"
channels = ["pytorch", "nvidia", "conda-forge"]
platforms = ["linux-64"]

[system-requirements]
linux = "3.10.0" 


[target.linux-64.dependencies]
_libgcc_mutex = "0.1.*"
_openmp_mutex = "*"
blas = "1.0.*"
brotlipy = "0.7.0.*"
bzip2 = "1.0.8.*"
ca-certificates = "2023.7.22.*"
certifi = "2023.7.22.*"
cffi = "1.15.1.*"
charset-normalizer = "2.0.4.*"
cryptography = "41.0.3.*"
cuda-cudart = "11.8.89.*"
cuda-cupti = "11.8.87.*"
cuda-libraries = "11.8.0.*"
cuda-nvrtc = "11.8.89.*"
cuda-nvtx = "11.8.86.*"
cuda-runtime = "11.8.0.*"
ffmpeg = "*"
filelock = "3.9.0.*"
freetype = "2.12.1.*"
giflib = "5.2.1.*"
gmp = "*"
gmpy2 = "*"
gnutls = "*"
idna = "3.4.*"
jinja2 = "3.1.2.*"
jpeg = "9e.*"
lame = "3.100.*"
lcms2 = "*"
ld_impl_linux-64 = "2.43.*"
lerc = "*"
libcublas = "11.11.3.6.*"
libcufft = "10.9.0.58.*"
libcufile = "1.7.2.10.*"
libcurand = "10.3.3.141.*"
libcusolver = "11.4.1.48.*"
libcusparse = "11.7.5.86.*"
libdeflate = "*"
libffi = "3.4.2.*"
libgcc-ng = "*"
libgomp = "*"
libiconv = "1.16.*"
libidn2 = "2.3.4.*"
libnpp = "11.8.0.86.*"
libnvjpeg = "11.9.0.86.*"
libpng = "1.6.39.*"
libstdcxx-ng = "*"
libtasn1 = "4.19.0.*"
libtiff = "*"
libunistring = "0.9.10.*"
libwebp = "*"
libwebp-base = "1.2.4.*"
lz4-c = "1.9.4.*"
markupsafe = "2.1.1.*"
mkl = "*"
mkl-service = "*"
mkl_fft = "*"
mkl_random = "*"
mpc = "1.1.0.*"
mpfr = "4.0.2.*"
mpmath = "1.3.0.*"
ncurses = "6.4.*"
nettle = "*"
networkx = "3.1.*"
numpy = "1.24.*"
openh264 = "2.1.1.*"
openssl = "*"
pillow = "*"
pip = "23.2.1.*"
pycparser = "2.21.*"
pyopenssl = "23.2.0.*"
pysocks = "1.7.1.*"
python = "3.8.18.*"
pytorch = "2.0.1.*"
pytorch-cuda = "11.8.*"
pytorch-mutex = "1.0.*"
readline = "8.2.*"
requests = "2.31.0.*"
setuptools = "68.0.0.*"
sqlite = "*"
sympy = "1.11.1.*"
tbb = "*"
tk = "*"
torchaudio = "2.0.2.*"
torchtriton = "2.0.0.*"
torchvision = "0.15.2.*"
typing_extensions = "4.7.1.*"
urllib3 = "1.26.16.*"
wheel = "0.38.4.*"
xz = "*"
zlib = "1.2.13.*"
zstd = "1.5.5.*"

[target.linux-64.pypi-dependencies]
appdirs = { version = "==1.4.4" }
click = { version = "==8.1.7" }
cycler = { version = "==0.11.0" }
docker-pycreds = { version = "==0.4.0" }
fonttools = { version = "==4.42.1" }
gitdb = { version = "==4.0.10" }
gitpython = { version = "==3.1.36" }
kiwisolver = { version = "==1.4.5" }
matplotlib = { version = "==3.5.2" }
mrcfile = { version = "==1.4.3" }
opencv-python = { version = "==4.7.0.72" }
packaging = { version = "==23.1" }
pathtools = { version = "==0.1.2" }
protobuf = { version = "==4.24.3" }
psutil = { version = "==5.9.5" }
pyparsing = { version = "==3.1.1" }
python-dateutil = { version = "==2.8.2" }
pyyaml = { version = "==6.0.1" }
scipy = { version = "==1.9.1" }
segment-anything = { version = "==1.0" }
sentry-sdk = { version = "==1.31.0" }
setproctitle = { version = "==1.3.2" }
six = { version = "==1.16.0" }
smmap = { version = "==5.0.0" }
tqdm = { version = "==4.64.1" }
wandb = { version = "==0.13.10" }
```

**Comment by rajangyawali** [comment]
Thank you so much for coming up with this new solution. We really appreciate your hard work.

**Comment by FerdKrupp** [comment]
Hi, 

I also had problems with installing and had to change the enviroment.yml to the following to work. I used `conda-forge` as the main channel and removed `defaultsi`. 
Also, the explicit versions could not be resolved by mamba (specifically the low level packages) in a several cases and `opencv-python` needed to be installed via pip. 


```yml
name: cryosegnet
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pytorch=2.4.1
  - pytorch-cuda=11.8
  - torchvision=0.20.0
  - torchaudio=2.4.1
  - numpy
  - scipy
  - matplotlib
  - opencv
  - mrcfile
  - networkx
  - sympy
  - requests
  - filelock
  - jinja2
  - freetype
  - lcms2
  - pillow
  - zlib
  - libpng
  - xz
  - tbb
  - typing_extensions
  - setuptools
  - wheel
  - openssl
  - ca-certificates
  - certifi
  - cffi
  - pyopenssl
  - charset-normalizer
  - idna
  - urllib3
  - tk
  - readline
  - sqlite
  - zstd
  - lz4-c
  - libwebp
  - libtiff
  - pip:
      - opencv-python
      - segment-anything==1.0
      - wandb==0.13.10
      - click
      - tqdm
      - docker-pycreds
      - fonttools
      - gitdb
      - gitpython
      - kiwisolver
      - packaging
      - pathtools
      - protobuf
      - psutil
      - pyparsing
      - python-dateutil
      - pyyaml
      - sentry-sdk
      - setproctitle
      - six

```
